### PR TITLE
workaround the case of a non-public email

### LINKED ISSUE #69: Error creating commit: Invalid request
```
[INFO] --- site-maven-plugin:0.9:site (execution1) @ lolchatapi ---
[INFO] Creating 18 blobs
[INFO] Creating tree with 19 blob entries
[INFO] Merging with tree 9a11f1f5c5d4e3441cb3949dcf9e907fa6c1f1d0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.494 s
[INFO] Finished at: 2014-08-29T12:09:59+02:00
[INFO] Final Memory: 31M/267M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.9:site (execution1) on project lolchatapi: Error creating commit: Invalid request.
[ERROR] 
[ERROR] Expected data to be of type "object"; value was: nil.
[ERROR] Expected data to be of type "object"; value was: nil. (422)

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating commit: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:440)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.eclipse.egit.github.core.service.DataService.createCommit(DataService.java:397)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:434)
	... 22 more
```

Everything worked great 5 days ago, but today I started getting this error. Is there anything on my end that I can do?

### LINKED ISSUE #70: Expected data to be of type "object"; value was: nil
I'm getting this strange error since yesterday:

```
[INFO] --- site-maven-plugin:0.9:site (default) @ thindeck ---
[INFO] Creating 266 blobs
[INFO] Creating tree with 266 blob entries
[INFO] Merging with tree 38ea39dde5d53409ee335d390037329d0bf09a58
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:01 min
[INFO] Finished at: 2014-08-29T19:49:08+00:00
[INFO] Final Memory: 59M/489M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.9:site (default) on project thindeck: Error creating commit: Invalid request.
[ERROR]
[ERROR] Expected data to be of type "object"; value was: nil.
[ERROR] Expected data to be of type "object"; value was: nil. (422)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.github:site-maven-plugin:0.9:site (default) on project thindeck: Error creating commit: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating commit: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:440)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Invalid request.

Expected data to be of type "object"; value was: nil.
Expected data to be of type "object"; value was: nil. (422)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.eclipse.egit.github.core.service.DataService.createCommit(DataService.java:397)
	at com.github.maven.plugins.site.SiteMojo.execute(SiteMojo.java:434)
	... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Full log is here, if necessary: http://www.rultor.com/t/722-53921097

### LINKED ISSUE #73: site-maven-plugin v 0.10-SNAPSHOT
Upload crashes if the user has not entered a valid email address in his or hers profile. No hint is given to encourage the user to enter an email address.

### LINKED ISSUE #77: Error deploying when email address not public
The plugin fails to deploy to the mvn-repo branch unless the deployer's email address is public. This is a major inconvenience for users who do not wish to publicize their email address. Adding a public email address mitigates this problem.

The error manifests as follows:

```
[ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.10:site (default) on project api: Error creating commit: Server Error (500) -> [Help 1]
```

### PR DESCRIPTION
**Pull request by mprins**
As proposed by some others, this works around the issue of not having a public email address on your github profile.

close #69
close #70
close #71
close #73
close #77

### CODE REVIEW

File: github-site-plugin/src/main/java/com/github/maven/plugins/site/SiteMojo.java [hunk 1]
```diff
@@ -433,7 +433,7 @@ public void execute() throws MojoExecutionException {
 
             CommitUser author = new CommitUser();
             author.setName(user.getName());
-            author.setEmail(user.getEmail());
+            author.setEmail(userService.getEmails().get(0));
```
Comment (kevinsawicki) [inline github-site-plugin/src/main/java/com/github/maven/plugins/site/SiteMojo.java]: Should this use `user.getEmail()` when available and only fall back to `userService.getEmails().get(0)` when the first is null/empty?

Comment (mprins) [inline github-site-plugin/src/main/java/com/github/maven/plugins/site/SiteMojo.java]: that might work as well; you'd have to give it a try.
I don't know the specifics of of the egit api anymore and don't have time atm.

**Comment by kevinsawicki** [comment]
Thanks for this, apologies for the delay

**Comment by kevinsawicki** [comment]
Releasing 0.11 to Maven Central just now, thanks again.

**Comment by farolfo** [comment]
I'm not finding the site-maven-plugin:0.11 version. This might be due to a delay in the release buckets?

**Comment by kevinsawicki** [comment]
> This might be due to a delay in the release buckets?

Yeah, I think it still takes hours to sync to maven central.

You can use https://oss.sonatype.org/#nexus-search;quick~github-maven-plugins in the interim if you need.
